export const PAGES = {
  HOME_PAGE: "/home",
  GROUP: "/groups",
  SETTING: "/settings",
  FORGOT_PASSWORD: "/forgot-password",
  LOGIN: "/login",
  PROFILE: "/profile",
  MESS: "/mess",
  MARKETING: "marketing",
  LANDING: "/landing",
  SERVICES: "/services",
  CASE_STUDIES: "/case-studies",
  CASE_STUDY: "/case-study",
  BLOG_POSTS: "/blog-posts",
  BLOG_POST: "/blog-post",
  ABOUT: "/about",
  CONTACT: "/contact",
  TRAVEL: "/travel",
  TOURS: "/tours",
  TOUR: "/tour",
  CHECKOUT: "/checkout",
  CHECKOUT_COMPLETE: "/checkout-complete",
};
